# Jabber configuration file

# The configuration specifies the following keys:
# * jabber_id  - Identidy (username) of the user
# * host       - Host to connect to (optional)
# * port       - Port to connect to (optional)
# * password   - Password used to authenticate
# * resource   - Multiple connections can be made with the same credentials and different resources
# * masters    - Array of Jabber ID's whose messages will be processed
# * supporters - Additional 'buddies' to keep on roster, but messages won't be processed (optional)
# * enable_logging - Enable Blather logging (VERY VERBOSE)
# * require_master - Disable filtering of messages based on the sender being a 'master'

defaults: &defaults
  jabber_id: dk@jabber.org
  host: jabber.org
  port: 5222
  password: secret
  resource: daemon_kit
  enable_logging: false
  masters:
    - kenneth.kalmer@gmail.com
  supporters:
    - someone@gmail.com

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
